apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stomasr
  name: stomasr
  namespace: limdongjin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stomasr
  strategy: {}
  template:
    metadata:
      labels:
        app: stomasr
    spec:
      serviceAccountName: stomasr
      containers:
        - image: gcr.io/limdongjin-kube/stomasr
          name: stomasr
          resources:
            requests:
              cpu: "10m"
              memory: 200Mi
            limits:
              cpu: "20m"
              memory: 400Mi
          ports:
            - containerPort: 8080
          env:
            - name: MYPORT
              value: "8080"
            - name: ALLOWORIGIN
              # value: https://limdongjin-kube.du.r.appspot.com
              value: "https://kafasr.limdongjin.com"
            - name: BOOTSTRAPSERVERS
              value: my-cluster-kafka-bootstrap.kafka-cluster:9092
            - name: SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: SASL_MECHANISM
              value: "SCRAM-SHA-512"
            - name: SASLJAASCONFIG
              valueFrom:
                secretKeyRef:
                  name: stomasr
                  key: "sasl.jaas.config"
status: {}

