apiVersion: v1
kind: Service
metadata:
  name: stomasr
  namespace: limdongjin
  #annotations:
  #  cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
  #  cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: stomasr
spec:
  type: NodePort
  selector:
    app: stomasr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#    - name: my-https-port
#      port: 443
#      protocol: TCP
#      targetPort: 8443
