version: '3'

services:
  ignite:
    image: apacheignite/ignite:2.14.0
    environment:
      - IGNITE_QUIET=false
      - CONFIG_URI=/config-file.xml
      - JVM_OPTS=-server -Xms512m -Xmx512m -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps 
      - IGNITE_DUMP_THREADS_ON_FAILURE_THROTTLING_TIMEOUT=0
    volumes:
      - ./ignite-config.xml:/config-file.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    restart: unless-stopped
    networks:
      - mybridge-network
  dlytaudio:
    image: limdongjin/dlytaudio
    restart: always
    environment:
      BOOTSTRAPSERVERS: ${BOOTSTRAPSERVERS}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USER_NAME: ${KAFKA_USER_NAME}
      KAFKA_USER_PASSWORD: ${KAFKA_USER_PASSWORD}
      IGNITE_SERVICE_NAME: ${IGNITE_SERVICE_NAME} 
      IGNITE_PORT: ${IGNITE_PORT}
      BQ_CREDENTIALS_JSON_FILE: ${BQ_CREDENTIALS_JSON_FILE}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - ./secrets/bq-config.json:${BQ_CREDENTIALS_JSON_FILE}
    networks:
      - mybridge-network
  sid:
    image: limdongjin/sid
    restart: always
    environment:
      BOOTSTRAPSERVERS: ${BOOTSTRAPSERVERS}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USER_NAME: ${KAFKA_USER_NAME}
      KAFKA_USER_PASSWORD: ${KAFKA_USER_PASSWORD}
      IGNITE_SERVICE_NAME: ${IGNITE_SERVICE_NAME} 
      IGNITE_PORT: ${IGNITE_PORT}
      BQ_CREDENTIALS_JSON_FILE: ${BQ_CREDENTIALS_JSON_FILE}
    volumes:
      - ./secrets/bq-config.json:${BQ_CREDENTIALS_JSON_FILE}
    networks:
      - mybridge-network
  searchyt:
    image: limdongjin/searchyt
    restart: always
    environment:
      BOOTSTRAPSERVERS: ${BOOTSTRAPSERVERS}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USER_NAME: ${KAFKA_USER_NAME}
      KAFKA_USER_PASSWORD: ${KAFKA_USER_PASSWORD}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - mybridge-network
  bqproducer:
    image: limdongjin/bqproducer
    restart: always
    environment:
      BOOTSTRAPSERVERS: ${BOOTSTRAPSERVERS}
      KAFKA_SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL}
      KAFKA_SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      KAFKA_USER_NAME: ${KAFKA_USER_NAME}
      KAFKA_USER_PASSWORD: ${KAFKA_USER_PASSWORD}
      BQ_CREDENTIALS_JSON_FILE: ${BQ_CREDENTIALS_JSON_FILE}
      BQ_DATASET_NAME: ${BQ_DATASET_NAME}
      BQ_TABLE_NAME: ${BQ_TABLE_NAME}
    volumes:
      - ./secrets/bq-config.json:${BQ_CREDENTIALS_JSON_FILE}
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - mybridge-network
  ignasr:
    image: limdongjin/ignasr
    restart: always
    ports:
      - 8088:8088
    environment:
      MYPORT: 8088
      ALLOWORIGIN: "*"
      BOOTSTRAPSERVERS: ${BOOTSTRAPSERVERS}
      SASLJAASCONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USER_NAME}' password='${KAFKA_USER_PASSWORD}';"
      SECURITY_PROTOCOL: ${KAFKA_SECURITY_PROTOCOL} 
      SASL_MECHANISM: ${KAFKA_SASL_MECHANISM}
      IGNITEMODE: local
      NAMESPACE: unused
      IGNITESERVICENAME: unused
      IGNITEADDRESSES: "${IGNITE_SERVICE_NAME}:${IGNITE_PORT}"
      GCP_CREDENTIALS_LOCATION: "file:${BQ_CREDENTIALS_JSON_FILE}"
    volumes:
      - ./secrets/bq-config.json:${BQ_CREDENTIALS_JSON_FILE}
    networks:
      - mybridge-network
networks:
  mybridge-network:
    driver: bridge
