apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: infer-positive 
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 5
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
