apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: user-pending 
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 180000
    segment.bytes: 1073741824
