// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/analysis_request.proto

package limdongjin.ignasr.protos;

public interface AnalysisRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:limdongjin.ignasr.protos.AnalysisRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   * @return The reqId.
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   * @return The bytes for reqId.
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>string userId = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string url = 3;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 3;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
