// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/analysis_request.proto

package limdongjin.ignasr.protos;

public final class AnalysisRequestProto {
  private AnalysisRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_limdongjin_ignasr_protos_AnalysisRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_limdongjin_ignasr_protos_AnalysisRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)resources/protobuf/analysis_request.pr" +
      "oto\022\030limdongjin.ignasr.protos\"=\n\017Analysi" +
      "sRequest\022\r\n\005reqId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022" +
      "\013\n\003url\030\003 \001(\tB\030B\024AnalysisRequestProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_limdongjin_ignasr_protos_AnalysisRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_limdongjin_ignasr_protos_AnalysisRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_limdongjin_ignasr_protos_AnalysisRequest_descriptor,
        new java.lang.String[] { "ReqId", "UserId", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
