// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/search_request.proto

package limdongjin.ignasr.protos;

public final class SearchRequestProto {
  private SearchRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_limdongjin_ignasr_protos_SearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_limdongjin_ignasr_protos_SearchRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'resources/protobuf/search_request.prot" +
      "o\022\030limdongjin.ignasr.protos\"o\n\rSearchReq" +
      "uest\022\r\n\005reqId\030\001 \001(\t\022\016\n\006userId\030\002 \001(\t\022\017\n\007k" +
      "eyword\030\003 \001(\t\022\020\n\010limitNum\030\004 \001(\005\022\034\n\024limitD" +
      "urationSeconds\030\005 \001(\005B\026B\022SearchRequestPro" +
      "toP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_limdongjin_ignasr_protos_SearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_limdongjin_ignasr_protos_SearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_limdongjin_ignasr_protos_SearchRequest_descriptor,
        new java.lang.String[] { "ReqId", "UserId", "Keyword", "LimitNum", "LimitDurationSeconds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
