apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: sid 
  name: sid
  namespace: limdongjin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sid
  template:
    metadata:
      labels:
        app: sid 
    spec:
      serviceAccountName: sid
      containers:
        - image: gcr.io/limdongjin-kube/sid
          name: sid
          resources:
            requests:
              cpu: "300m"
              memory: 1Gi
              ephemeral-storage: "2Gi"
            limits:
              cpu: "500m"
              memory: 2Gi
              ephemeral-storage: "7Gi"
          env:
            - name: BOOTSTRAPSERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka_info
                  key: bootstrap_servers
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: kafka_info
                  key: security_protocol
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                secretKeyRef:
                  name: kafka_info
                  key: sasl_mechanism 
            - name: KAFKA_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka_info
                  key: user_name
            - name: KAFKA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka_info
                  key: user_password
