// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/search_request.proto

package limdongjin.ignasr.protos;

public interface SearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:limdongjin.ignasr.protos.SearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reqId = 1;</code>
   * @return The reqId.
   */
  java.lang.String getReqId();
  /**
   * <code>string reqId = 1;</code>
   * @return The bytes for reqId.
   */
  com.google.protobuf.ByteString
      getReqIdBytes();

  /**
   * <code>string userId = 2;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string keyword = 3;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <code>string keyword = 3;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();

  /**
   * <code>int32 limitNum = 4;</code>
   * @return The limitNum.
   */
  int getLimitNum();

  /**
   * <code>int32 limitDurationSeconds = 5;</code>
   * @return The limitDurationSeconds.
   */
  int getLimitDurationSeconds();
}
