apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: stomasr
  namespace: kafka-cluster
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: user-pending
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
          - AlterConfigs
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operations:
          - Read
        host: "*"
      - resource:
          type: topic
          name: infer-positive
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
          - AlterConfigs
        host: "*"
      - resource:
          type: topic
          name: infer-negative
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
          - AlterConfigs
        host: "*"
