apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stomasr
  name: stomasr
  namespace: limdongjin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stomasr
  strategy: {}
  template:
    metadata:
      labels:
        app: stomasr
    spec:
      serviceAccountName: stomasr
      containers:
        - image: gcr.io/limdongjin-kube/stomasr:v6
          name: stomasr
          resources:
            limits:
              cpu: 2000m
              ephemeral-storage: 2Gi
              memory: 3Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          env:
            - name: BOOTSTRAPSERVERS
              value: my-cluster-kafka-bootstrap:9092
            - name: SASLJAASCONFIG
              valueFrom:
                secretKeyRef:
                  name: stomasr
                  key: "sasl.jaas.config"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: stomasr
  name: stomasr
  namespace: limdongjin
spec:
  ports:
  - name: 8089-8089
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: stomasr 
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: stomasr
  namespace: limdongjin
  annotations:
    kubernetes.io/ingress.global-static-ip-name: web-static-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: stomasr-service
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stomasr-service
  namespace: limdongjin
  labels:
    app: stomasr
spec:
  type: NodePort
  selector:
    app: stomasr
  ports:
  - port: 8080
    targetPort: 8080

