apiVersion: v1
kind: Service
metadata:
  name: stomasr
  namespace: limdongjin
  labels:
    app: stomasr
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: stomasr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
# equivalent command:
#   kubectl expose deployment ignasr
