server:
  port: 8089

limdongjin:
  stomasr:
    cors:
      origin: localhost:8080
    kafka:
      bootstrapservers: localhost:29092
      sasljaasconfig: unused
      security-protocol: PLAINTEXT
      sasl-mechanism: unused
spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        allow.auto.create.topics: true