// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/infer.proto

package limdongjin.stomasr.protos;

public final class InferProto {
  private InferProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:limdongjin.stomasr.protos.Infer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reqId = 1;</code>
     * @return The reqId.
     */
    java.lang.String getReqId();
    /**
     * <code>string reqId = 1;</code>
     * @return The bytes for reqId.
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    /**
     * <code>string inferResult = 2;</code>
     * @return The inferResult.
     */
    java.lang.String getInferResult();
    /**
     * <code>string inferResult = 2;</code>
     * @return The bytes for inferResult.
     */
    com.google.protobuf.ByteString
        getInferResultBytes();

    /**
     * <code>optional string label = 3;</code>
     * @return Whether the label field is set.
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 3;</code>
     * @return The label.
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 3;</code>
     * @return The bytes for label.
     */
    com.google.protobuf.ByteString
        getLabelBytes();

    /**
     * <code>optional string score = 4;</code>
     * @return Whether the score field is set.
     */
    boolean hasScore();
    /**
     * <code>optional string score = 4;</code>
     * @return The score.
     */
    java.lang.String getScore();
    /**
     * <code>optional string score = 4;</code>
     * @return The bytes for score.
     */
    com.google.protobuf.ByteString
        getScoreBytes();

    /**
     * <code>optional string info = 5;</code>
     * @return Whether the info field is set.
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 5;</code>
     * @return The info.
     */
    java.lang.String getInfo();
    /**
     * <code>optional string info = 5;</code>
     * @return The bytes for info.
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    /**
     * <code>optional string transcription = 6;</code>
     * @return Whether the transcription field is set.
     */
    boolean hasTranscription();
    /**
     * <code>optional string transcription = 6;</code>
     * @return The transcription.
     */
    java.lang.String getTranscription();
    /**
     * <code>optional string transcription = 6;</code>
     * @return The bytes for transcription.
     */
    com.google.protobuf.ByteString
        getTranscriptionBytes();
  }
  /**
   * Protobuf type {@code limdongjin.stomasr.protos.Infer}
   */
  public static final class Infer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:limdongjin.stomasr.protos.Infer)
      InferOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Infer.newBuilder() to construct.
    private Infer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Infer() {
      reqId_ = "";
      inferResult_ = "";
      label_ = "";
      score_ = "";
      info_ = "";
      transcription_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Infer();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return limdongjin.stomasr.protos.InferProto.internal_static_limdongjin_stomasr_protos_Infer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return limdongjin.stomasr.protos.InferProto.internal_static_limdongjin_stomasr_protos_Infer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              limdongjin.stomasr.protos.InferProto.Infer.class, limdongjin.stomasr.protos.InferProto.Infer.Builder.class);
    }

    private int bitField0_;
    public static final int REQID_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string reqId = 1;</code>
     * @return The reqId.
     */
    @java.lang.Override
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string reqId = 1;</code>
     * @return The bytes for reqId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFERRESULT_FIELD_NUMBER = 2;
    private volatile java.lang.Object inferResult_;
    /**
     * <code>string inferResult = 2;</code>
     * @return The inferResult.
     */
    @java.lang.Override
    public java.lang.String getInferResult() {
      java.lang.Object ref = inferResult_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inferResult_ = s;
        return s;
      }
    }
    /**
     * <code>string inferResult = 2;</code>
     * @return The bytes for inferResult.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInferResultBytes() {
      java.lang.Object ref = inferResult_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inferResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LABEL_FIELD_NUMBER = 3;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 3;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string label = 3;</code>
     * @return The label.
     */
    @java.lang.Override
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>optional string label = 3;</code>
     * @return The bytes for label.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 4;
    private volatile java.lang.Object score_;
    /**
     * <code>optional string score = 4;</code>
     * @return Whether the score field is set.
     */
    @java.lang.Override
    public boolean hasScore() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string score = 4;</code>
     * @return The score.
     */
    @java.lang.Override
    public java.lang.String getScore() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        score_ = s;
        return s;
      }
    }
    /**
     * <code>optional string score = 4;</code>
     * @return The bytes for score.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScoreBytes() {
      java.lang.Object ref = score_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        score_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFO_FIELD_NUMBER = 5;
    private volatile java.lang.Object info_;
    /**
     * <code>optional string info = 5;</code>
     * @return Whether the info field is set.
     */
    @java.lang.Override
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string info = 5;</code>
     * @return The info.
     */
    @java.lang.Override
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>optional string info = 5;</code>
     * @return The bytes for info.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRANSCRIPTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object transcription_;
    /**
     * <code>optional string transcription = 6;</code>
     * @return Whether the transcription field is set.
     */
    @java.lang.Override
    public boolean hasTranscription() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string transcription = 6;</code>
     * @return The transcription.
     */
    @java.lang.Override
    public java.lang.String getTranscription() {
      java.lang.Object ref = transcription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transcription_ = s;
        return s;
      }
    }
    /**
     * <code>optional string transcription = 6;</code>
     * @return The bytes for transcription.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTranscriptionBytes() {
      java.lang.Object ref = transcription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transcription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inferResult_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, inferResult_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, label_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, score_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, info_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, transcription_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(reqId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(inferResult_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, inferResult_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, label_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, score_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, info_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, transcription_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof limdongjin.stomasr.protos.InferProto.Infer)) {
        return super.equals(obj);
      }
      limdongjin.stomasr.protos.InferProto.Infer other = (limdongjin.stomasr.protos.InferProto.Infer) obj;

      if (!getReqId()
          .equals(other.getReqId())) return false;
      if (!getInferResult()
          .equals(other.getInferResult())) return false;
      if (hasLabel() != other.hasLabel()) return false;
      if (hasLabel()) {
        if (!getLabel()
            .equals(other.getLabel())) return false;
      }
      if (hasScore() != other.hasScore()) return false;
      if (hasScore()) {
        if (!getScore()
            .equals(other.getScore())) return false;
      }
      if (hasInfo() != other.hasInfo()) return false;
      if (hasInfo()) {
        if (!getInfo()
            .equals(other.getInfo())) return false;
      }
      if (hasTranscription() != other.hasTranscription()) return false;
      if (hasTranscription()) {
        if (!getTranscription()
            .equals(other.getTranscription())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      hash = (37 * hash) + INFERRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getInferResult().hashCode();
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      if (hasScore()) {
        hash = (37 * hash) + SCORE_FIELD_NUMBER;
        hash = (53 * hash) + getScore().hashCode();
      }
      if (hasInfo()) {
        hash = (37 * hash) + INFO_FIELD_NUMBER;
        hash = (53 * hash) + getInfo().hashCode();
      }
      if (hasTranscription()) {
        hash = (37 * hash) + TRANSCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getTranscription().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static limdongjin.stomasr.protos.InferProto.Infer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(limdongjin.stomasr.protos.InferProto.Infer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code limdongjin.stomasr.protos.Infer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:limdongjin.stomasr.protos.Infer)
        limdongjin.stomasr.protos.InferProto.InferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return limdongjin.stomasr.protos.InferProto.internal_static_limdongjin_stomasr_protos_Infer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return limdongjin.stomasr.protos.InferProto.internal_static_limdongjin_stomasr_protos_Infer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                limdongjin.stomasr.protos.InferProto.Infer.class, limdongjin.stomasr.protos.InferProto.Infer.Builder.class);
      }

      // Construct using limdongjin.stomasr.protos.InferProto.Infer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        reqId_ = "";

        inferResult_ = "";

        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        score_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        transcription_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return limdongjin.stomasr.protos.InferProto.internal_static_limdongjin_stomasr_protos_Infer_descriptor;
      }

      @java.lang.Override
      public limdongjin.stomasr.protos.InferProto.Infer getDefaultInstanceForType() {
        return limdongjin.stomasr.protos.InferProto.Infer.getDefaultInstance();
      }

      @java.lang.Override
      public limdongjin.stomasr.protos.InferProto.Infer build() {
        limdongjin.stomasr.protos.InferProto.Infer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public limdongjin.stomasr.protos.InferProto.Infer buildPartial() {
        limdongjin.stomasr.protos.InferProto.Infer result = new limdongjin.stomasr.protos.InferProto.Infer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.reqId_ = reqId_;
        result.inferResult_ = inferResult_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.label_ = label_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.score_ = score_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.transcription_ = transcription_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof limdongjin.stomasr.protos.InferProto.Infer) {
          return mergeFrom((limdongjin.stomasr.protos.InferProto.Infer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(limdongjin.stomasr.protos.InferProto.Infer other) {
        if (other == limdongjin.stomasr.protos.InferProto.Infer.getDefaultInstance()) return this;
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        if (!other.getInferResult().isEmpty()) {
          inferResult_ = other.inferResult_;
          onChanged();
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000001;
          label_ = other.label_;
          onChanged();
        }
        if (other.hasScore()) {
          bitField0_ |= 0x00000002;
          score_ = other.score_;
          onChanged();
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000004;
          info_ = other.info_;
          onChanged();
        }
        if (other.hasTranscription()) {
          bitField0_ |= 0x00000008;
          transcription_ = other.transcription_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                reqId_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                inferResult_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                label_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 26
              case 34: {
                score_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 34
              case 42: {
                info_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 42
              case 50: {
                transcription_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object reqId_ = "";
      /**
       * <code>string reqId = 1;</code>
       * @return The reqId.
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reqId = 1;</code>
       * @return The bytes for reqId.
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqId = 1;</code>
       * @param value The reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string reqId = 1;</code>
       * @param value The bytes for reqId to set.
       * @return This builder for chaining.
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object inferResult_ = "";
      /**
       * <code>string inferResult = 2;</code>
       * @return The inferResult.
       */
      public java.lang.String getInferResult() {
        java.lang.Object ref = inferResult_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          inferResult_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string inferResult = 2;</code>
       * @return The bytes for inferResult.
       */
      public com.google.protobuf.ByteString
          getInferResultBytes() {
        java.lang.Object ref = inferResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          inferResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string inferResult = 2;</code>
       * @param value The inferResult to set.
       * @return This builder for chaining.
       */
      public Builder setInferResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        inferResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string inferResult = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearInferResult() {
        
        inferResult_ = getDefaultInstance().getInferResult();
        onChanged();
        return this;
      }
      /**
       * <code>string inferResult = 2;</code>
       * @param value The bytes for inferResult to set.
       * @return This builder for chaining.
       */
      public Builder setInferResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        inferResult_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 3;</code>
       * @return Whether the label field is set.
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string label = 3;</code>
       * @return The label.
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       * @return The bytes for label.
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 3;</code>
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 3;</code>
       * @param value The bytes for label to set.
       * @return This builder for chaining.
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000001;
        label_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object score_ = "";
      /**
       * <code>optional string score = 4;</code>
       * @return Whether the score field is set.
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string score = 4;</code>
       * @return The score.
       */
      public java.lang.String getScore() {
        java.lang.Object ref = score_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          score_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string score = 4;</code>
       * @return The bytes for score.
       */
      public com.google.protobuf.ByteString
          getScoreBytes() {
        java.lang.Object ref = score_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          score_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string score = 4;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = getDefaultInstance().getScore();
        onChanged();
        return this;
      }
      /**
       * <code>optional string score = 4;</code>
       * @param value The bytes for score to set.
       * @return This builder for chaining.
       */
      public Builder setScoreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000002;
        score_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>optional string info = 5;</code>
       * @return Whether the info field is set.
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string info = 5;</code>
       * @return The info.
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string info = 5;</code>
       * @return The bytes for info.
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 5;</code>
       * @param value The info to set.
       * @return This builder for chaining.
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 5;</code>
       * @param value The bytes for info to set.
       * @return This builder for chaining.
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000004;
        info_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object transcription_ = "";
      /**
       * <code>optional string transcription = 6;</code>
       * @return Whether the transcription field is set.
       */
      public boolean hasTranscription() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string transcription = 6;</code>
       * @return The transcription.
       */
      public java.lang.String getTranscription() {
        java.lang.Object ref = transcription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          transcription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string transcription = 6;</code>
       * @return The bytes for transcription.
       */
      public com.google.protobuf.ByteString
          getTranscriptionBytes() {
        java.lang.Object ref = transcription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          transcription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string transcription = 6;</code>
       * @param value The transcription to set.
       * @return This builder for chaining.
       */
      public Builder setTranscription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        transcription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string transcription = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTranscription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        transcription_ = getDefaultInstance().getTranscription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string transcription = 6;</code>
       * @param value The bytes for transcription to set.
       * @return This builder for chaining.
       */
      public Builder setTranscriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        bitField0_ |= 0x00000008;
        transcription_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:limdongjin.stomasr.protos.Infer)
    }

    // @@protoc_insertion_point(class_scope:limdongjin.stomasr.protos.Infer)
    private static final limdongjin.stomasr.protos.InferProto.Infer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new limdongjin.stomasr.protos.InferProto.Infer();
    }

    public static limdongjin.stomasr.protos.InferProto.Infer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Infer>
        PARSER = new com.google.protobuf.AbstractParser<Infer>() {
      @java.lang.Override
      public Infer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Infer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Infer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public limdongjin.stomasr.protos.InferProto.Infer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_limdongjin_stomasr_protos_Infer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_limdongjin_stomasr_protos_Infer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036resources/protobuf/infer.proto\022\031limdon" +
      "gjin.stomasr.protos\"\261\001\n\005Infer\022\r\n\005reqId\030\001" +
      " \001(\t\022\023\n\013inferResult\030\002 \001(\t\022\022\n\005label\030\003 \001(\t" +
      "H\000\210\001\001\022\022\n\005score\030\004 \001(\tH\001\210\001\001\022\021\n\004info\030\005 \001(\tH" +
      "\002\210\001\001\022\032\n\rtranscription\030\006 \001(\tH\003\210\001\001B\010\n\006_lab" +
      "elB\010\n\006_scoreB\007\n\005_infoB\020\n\016_transcriptionB" +
      "\'\n\031limdongjin.stomasr.protosB\nInferProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_limdongjin_stomasr_protos_Infer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_limdongjin_stomasr_protos_Infer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_limdongjin_stomasr_protos_Infer_descriptor,
        new java.lang.String[] { "ReqId", "InferResult", "Label", "Score", "Info", "Transcription", "Label", "Score", "Info", "Transcription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
