server:
  port: ${MYPORT}

spring:
  cloud:
    gcp:
      core:
        enabled: true
      datastore:
        project-id: limdongjin-kube
        credentials:
          location: ${GCP_CREDENTIALS_LOCATION}
        enabled: true
logging:
  level:
    org.springframework.*: DEBUG
    io.netty.*: DEBUG
    limdongjin.ignasr.*: DEBUG
limdongjin:
  ignasr:
    security:
      token:  -----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCf4+vXNS+yfQ9y\nO961XGyoOk3R5hjtqOL6BAOuRo1zlXHeGFSl+fH8SA1lQaUqwPRPc76d/x/V0F4q\nJ+RdGbjkOc6Wi67owju895BhLSTi4xFQ5ucfr7Y0gOovVRTVZOIdszhny/i9PTOp\ndjOHP9gjsgnc94q501W1KvcXEWhGOx2YeBVWy0SSr0IywlMpT6WJ6drkDQGbcQ9a\npOjUrgcpKQPo4lMSXL7Cyh0c2+tkty8P6ojGEHirNnPmPaYZAHUPtKwoTvZzHWFo\ns81yuw/+TCwTI073OqtbHJsyFZOizkZJsunlmRU8OcG8k9OpYGShxpW8CMW/CeoM\nT2Cwi8WZAgMBAAECggEAck362IuJYczOMhhjCrzcYRftclVRFPZb7ejYyMpfbXY1\nRVWXjmC1gmnwSac4cOwovHQ+na06ER05dGG4fGZbK6235yBNFtFk658AdLhVWm6C\nfpfUO27ej4Jp6RSmJDhO/nSVqn7DgGY0fL2n8NTPrBUnv/SoFFjlOPNSWgdzyGBx\nQRM8Ci8FhDBPc+Ry0pzrRpk8udWphGKocEqUKkSVjFFZW9KLCcNLvtfEAu2l+te+\n+9ATX5rmDeTIfRLR/T1WMUklglCIbHxI/gS4T9Ymqf93adoiyJzyGs5LljvSWrI0\n3Ih9KLwYYWHfUw4Cg33i0mwLFQnbgn3OY4yNdKLIAQKBgQDRen6qcYG96swaK2HW\ndkRUObG9GYdTpBN/hXoVPwSCR191U0Op81j15JSmcdw1YyBuE6eqM828QEuLU6kx\n8uO4xnCL7Jwoyo45mFCzysGSCogseOsprQUqmKPPGmShLwE7RJ5GgHqNionNj0/R\nm0wicHop2v3VOpaMFdTx1qGE2QKBgQDDZi8cnxGerhAHX/AtBHAFIDLaTf7EAgIn\nwoeJk0wx2IxZ0UmPMrzw3/AqDDo29Ep88yyaQEQlyAfgaP3ZRsptvjizp75fQgdP\n4qvYpzfP0v3jLq3WSX091nfM9sHh3yejic4ZegG9Uh7NyuJeUrR5AYFqA/EUr+/g\nTg+uuuDOwQKBgQCv/zDo1xDglaMB4a0D2L2z3f1dGVO/jDztiSF3NEj/hCPJmTli\nUphNj8zswwD2wd//W/gkYf3aylIuLw4aby2wktkAVr0k8HnqHfS/+fwETWD3rGg3\nzaxni3Mlj9E4MxvfxdkM9ukAfoMk9+FiBA5FaSbaf6mAOwc9jyIoReHSkQKBgD2l\nS0+4T5LET4JEHj3VnJHBasm8uZeVGqD4mlIpCmzfaMgdYxuuYjWMMPTTDrqvr6Bk\nB7pSdC2HQhTmis+1qb+dt73WOhVLe4sUdCrR9qW2Zyr5Wxaz8LNFql4bq2dbQ+Iw\nY7ld6JaWBenfDDO92/ohI3cS70gbiY42knQJuUsBAoGAcNDUhAwy/lqIBLwKyQ5d\n9EosCPaNfNYW5GW6WFPVC0G3Dy6ZWa0mknyDeem9i3gZUgWPxH/95lgvd3kKcahS\nUu457omsn8/N97PM8ICxYDnpwewDY0nXTFvo3TXO+TpaINNNrKkGf1T2vu0JnWmj\n7ITlKjW0Etg5THX8ie4snt0=\n-----END PRIVATE KEY-----
        # ${TOKEN}
    cors:
      origin: ${ALLOWORIGIN}
    kafka:
      bootstrapservers: ${BOOTSTRAPSERVERS}
      sasljaasconfig: ${SASLJAASCONFIG}
      security-protocol: ${SECURITY_PROTOCOL} # SASL_PLAINTEXT or SASL_SSL
      sasl-mechanism: ${SASL_MECHANISM} # SCRAM-SHA-512 or PLAIN
    ignite:
      mode: ${IGNITEMODE} # kubernetes
      namespace: ${NAMESPACE}     # limdongjin
      servicename: ${IGNITESERVICENAME} # ignite-service
      addresses: ${IGNITEADDRESSES}     # ignite-service:10800

