// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/person_register.proto

package limdongjin.authserver.protos;

public final class PersonRegisterProto {
  private PersonRegisterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonRegister_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(resources/protobuf/person_register.pro" +
      "to\">\n\016PersonRegister\022\014\n\004name\030\001 \001(\t\022\020\n\010pa" +
      "ssword\030\002 \001(\t\022\014\n\004role\030\003 \001(\tB5\n\034limdongjin" +
      ".authserver.protosB\023PersonRegisterProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PersonRegister_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonRegister_descriptor,
        new java.lang.String[] { "Name", "Password", "Role", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
