apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: spbrain
  name: spbrain-t
  namespace: limdongjin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spbrain
  #serviceName: spbrain
  template:
    metadata:
      labels:
        app: spbrain
    spec:
      serviceAccountName: spbrain
      containers:
        - image: gcr.io/limdongjin-kube/spbrain-t
          name: spbrain-t
          resources:
            requests:
              cpu: 2
              memory: 2Gi
              ephemeral-storage: "2Gi"
            limits:
              cpu: 4
              memory: 5Gi
              ephemeral-storage: "7Gi"
          env:
            - name: BOOTSTRAPSERVERS
              value: "my-cluster-kafka-bootstrap.kafka-cluster:9092"
            - name: KAFKA_USER_NAME
              value: "spbrain-t"
            - name: KAFKA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spbrain-t
                  key: password
            - name: IGNITE_SERVICE_NAME
              value: "ignite-service"
            - name: IGNITE_PORT
              value: "10800"
            - name: CONSUMER_ASSIGN_STRATEGY
              value: "range,roundrobin"
   
