apiVersion: apps/v1
kind: Deployment 
metadata:
  labels:
    app: spbrain
  name: spbrain
  namespace: limdongjin
spec:
  replicas: 10
  selector:
    matchLabels:
      app: spbrain
  #serviceName: spbrain
  template:
    metadata:
      labels:
        app: spbrain
    spec:
      serviceAccountName: spbrain
      containers:
        - image: gcr.io/limdongjin-kube/spbrain
          name: spbrain
          resources:
            requests:
              cpu: "300m"
              memory: 1Gi
              ephemeral-storage: "2Gi"
            limits:
              cpu: "500m"
              memory: 2Gi
              ephemeral-storage: "7Gi"
          env:
            - name: BOOTSTRAPSERVERS
              value: "my-cluster-kafka-bootstrap.kafka-cluster:9092"
            - name: KAFKA_USER_NAME
              value: "spbrain"
            - name: KAFKA_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spbrain
                  key: password
            - name: IGNITE_SERVICE_NAME
              value: "ignite-service"
            - name: IGNITE_PORT
              value: "10800"
            - name: CONSUMER_ASSIGN_STRATEGY
              value: "range,roundrobin"
   
